---
- name: Download Prometheus tar
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/0.16.0/prometheus-0.16.0.linux-amd64.tar.gz
    dest: /usr/share/

- name: create a directory for prometheus
  file:
    path: /usr/share/prometheus
    state: directory
    mode: 0755

- name: unarchive the prometheus tar
  unarchive:
    src: /usr/share/prometheus-0.16.0.linux-amd64.tar.gz
    dest: /usr/share/prometheus
    remote_src: True

- name: Download the node exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
    dest: /usr/share/prometheus
    remote_src: True

- name: Install node_exporter init script
  template: src=node_exporter.service dest=/etc/systemd/system/ mode=0755

- name: Start node_exporter
  systemd: state=started name=node_exporter daemon_reload=yes enabled=True

- name: Copy the prometheus.yml file
  template: src=prometheus.yml.j2 dest=/usr/share/prometheus/prometheus-0.16.0.linux-amd64/prometheus.yml

- name: Install prometheus init script
  template: src=prometheus.service dest=/etc/systemd/system/ mode=0755

- name: Start prometheus
  systemd: state=started name=prometheus daemon_reload=yes enabled=True

- name: Copy the grafana.repo file
  template: src=grafana.repo dest=/etc/yum.repos.d/grafana.repo

- name: Install grafana
  yum:
    name: grafana
    state: installed
    update_cache: yes

- name: Start grafana-server
  systemd: state=started name=grafana-server daemon_reload=yes enabled=True
